package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Ratingcriteria generated by hbm2java
 */
@Entity
@Table(name = "ratingcriteria", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class RatingCriteria extends CommonEntity implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4352427783686766666L;

	private int id;
	private String name;
	private String description;
	private Set<TopicRatingCriteria> topicsRatingCriterias = null;
	private Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias = null;
	private RatingCriteria parentRatingCriteria;
	private Set<RatingCriteria> childRatingCriterias = null;
	private Short criteriaType;
	private int priority;

	/**
	 * 
	 */
	public RatingCriteria() {
		super();
	}

	/**
	 * @param name
	 */
	public RatingCriteria(String name) {
		super();
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ratingcriteria_id_seq")
	@SequenceGenerator(name = "ratingcriteria_id_seq", initialValue = 1, sequenceName = "ratingcriteria_id_seq", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
		this.setSortName(this.name);
	}
	
	@Override
	public void setSortName(String sortName){
		super.setSortName(sortName);
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ratingCriteria", cascade=CascadeType.ALL)
	public Set<TopicRatingCriteria> getTopicsRatingCriterias() {
		return topicsRatingCriterias;
	}

	/**
	 * @param topicsRatingCriterias the topicsRatingCriterias to set
	 */
	public void setTopicsRatingCriterias(
			Set<TopicRatingCriteria> topicsRatingCriterias) {
		this.topicsRatingCriterias = topicsRatingCriterias;
	}

	/**
	 * @return the siteReviewsRatingCriterias
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ratingCriteria" , cascade=CascadeType.ALL)
	public Set<SiteReviewRatingCriteria> getSiteReviewsRatingCriterias() {
		return siteReviewsRatingCriterias;
	}

	/**
	 * @param siteReviewsRatingCriterias the siteReviewsRatingCriterias to set
	 */
	public void setSiteReviewsRatingCriterias(
			Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias) {
		this.siteReviewsRatingCriterias = siteReviewsRatingCriterias;
	}

	/**
	 * @return the description
	 */
	@Column(name="description", columnDefinition="text")
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="parent_id")
	/**
	 * @return the parentRatingCriteria
	 */
	public RatingCriteria getParentRatingCriteria() {
		return parentRatingCriteria;
	}
	
	/**
	 * @param parentRatingCriteria the parentRatingCriteria to set
	 */
	public void setParentRatingCriteria(RatingCriteria parentRatingCriteria) {
		this.parentRatingCriteria = parentRatingCriteria;
	}

	
	@Basic
	@Column(name="priority", nullable=false, length=10)	
	/**
	 * @return the priority
	 */
	public int getPriority() {
		return priority;
	}
	
	/**
	 * @param priority the priority to set
	 */
	public void setPriority(int priority) {
		this.priority = priority;
	}

	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.ALL, mappedBy="parentRatingCriteria")
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	/**
	 * @return the childRatingCriterias
	 */
	public Set<RatingCriteria> getChildRatingCriterias() {
		return childRatingCriterias;
	}

	/**
	 * @param childRatingCriterias the childRatingCriterias to set
	 */
	public void setChildRatingCriterias(Set<RatingCriteria> childRatingCriterias) {
		this.childRatingCriterias = childRatingCriterias;
	}

	
	@Column(name="criteria_type")
	/**
	 * @return the criteriaType
	 */
	public Short getCriteriaType() {
		return criteriaType;
	}

	/**
	 * @param criteriaType the criteriaType to set
	 */
	public void setCriteriaType(Short criteriaType) {
		this.criteriaType = criteriaType;
	}
	
	@Override
	public String toString() {
		return "RatingCriteria [id=" + id + ", name=" + name + "]";
	}
}
