package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RelatedTopics generated by hbm2java
 */
@Entity
@Table(name = "related_topics", schema = "public")
public class RelatedTopics extends CommonEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String id;
	private Topic topics;
	private Topic relatedTopicId;
	
	
	
	/**
	 * @return the id
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="relatedtopics_id_seq")
	@SequenceGenerator(name="relatedtopics_id_seq", initialValue=1, sequenceName="relatedtopics_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id")
	public Topic getTopics() {
		return this.topics;
	}

	public void setTopics(Topic topics) {
		this.topics = topics;
	}
	/**
	 * @return the relatedTopicId
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "relatedtopic_id")
	public Topic getRelatedTopicId() {
		return relatedTopicId;
	}
	/**
	 * @param relatedTopicId the relatedTopicId to set
	 */
	public void setRelatedTopicId(Topic relatedTopicId) {
		this.relatedTopicId = relatedTopicId;
	}

}
