package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY)
public class Role extends CommonEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 326571666707801514L;
	
	private short id;
	private String name;

	public Role() {
	}

	public Role(short id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="roles_id_seq")
	@SequenceGenerator(name="roles_id_seq", initialValue=1, sequenceName="roles_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
		this.setSortName(this.name);
	}

	@Override
	public void setSortName(String sortName){
		super.setSortName(sortName);
	}
	
}
