package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Sitereviews generated by hbm2java
 */
@Entity
@Table(name = "sitereviews", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class SiteReview extends CommonEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3122358534861557426L;
	
	private long id;
	private User user;
	private Site site;
	private Topic topics;
	private Integer statusCode;
	private Integer score;
	private String description;
	private String evaluation;
	private String strength;
	private String weakness;
	private String searchvector;
	private int readStatus;
	private Short reviewStatus;
	private Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias = 
			new HashSet<SiteReviewRatingCriteria>(0);
	private Set<SiteReviewComments> siteReviewComments = new HashSet<>();

	public SiteReview() {
	}

	public SiteReview(long id) {
		this.id = id;
	}

	public SiteReview(long id, User user, Site site, Topic topics,
			Integer statusCode, Integer score, String description,
			String evaluation, Long createdBy, Date dateCreated,
			Date lastUpdated, Serializable uuid,
			Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias) {
		this.id = id;
		this.user = user;
		this.site = site;
		this.topics = topics;
		this.statusCode = statusCode;
		this.score = score;
		this.description = description;
		this.evaluation = evaluation;
		this.siteReviewsRatingCriterias = siteReviewsRatingCriterias;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="sitereviews_id_seq")
	@SequenceGenerator(name="sitereviews_id_seq", initialValue=1, sequenceName="sitereviews_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id")
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id")
	public Topic getTopics() {
		return this.topics;
	}

	public void setTopics(Topic topics) {
		this.topics = topics;
	}

	@Column(name = "status_code")
	public Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "description" ,  columnDefinition="text")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "evaluation" ,  columnDefinition="text")
	public String getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(String evaluation) {
		this.evaluation = evaluation;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "siteReviews" , cascade = CascadeType.REMOVE)
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public Set<SiteReviewRatingCriteria> getSiteReviewsRatingCriterias() {
		return this.siteReviewsRatingCriterias;
	}

	public void setSiteReviewsRatingCriterias(
			Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias) {
		this.siteReviewsRatingCriterias = siteReviewsRatingCriterias;
	}

	@Column(name="strength" ,  columnDefinition="text")
	/**
	 * @return the strength
	 */
	public String getStrength() {
		return strength;
	}

	/**
	 * @param strength the strength to set
	 */
	public void setStrength(String strength) {
		this.strength = strength;
	}

	
	@Column(name="weakness" ,  columnDefinition="text")
	/**
	 * @return the weakness
	 */
	public String getWeakness() {
		return weakness;
	}

	/**
	 * @param weakness the weakness to set
	 */
	public void setWeakness(String weakness) {
		this.weakness = weakness;
	}

	@Column(name="searchvector", columnDefinition="tsvector")
	/**
	 * @return the searchvector
	 */
	public String getSearchvector() {
		return searchvector;
	}

	/**
	 * @param searchvector the searchvector to set
	 */
	public void setSearchvector(String searchvector) {
		this.searchvector = searchvector;
	}

	@Column(name = "read_status")
	public int getReadStatus() {
		return readStatus;
	}

	public void setReadStatus(int readStatus) {
		this.readStatus = readStatus;
	}
	
	@Column(name="review_status")
	public Short getReviewStatus() {
		return reviewStatus;
	}
	
	public void setReviewStatus(Short reviewStatus) {
		this.reviewStatus = reviewStatus;
	}
	
	
	@OneToMany(fetch=FetchType.LAZY, cascade=CascadeType.REMOVE, mappedBy="siteReview")
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public Set<SiteReviewComments> getSiteReviewComments() {
		return siteReviewComments;
	}
	
	public void setSiteReviewComments(Set<SiteReviewComments> siteReviewComments) {
		this.siteReviewComments = siteReviewComments;
	}
	
}
