package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Index;

/**
 * Sites generated by hbm2java
 */
@Entity
@Table(name = "sites", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Site extends CommonEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2013134351059546201L;
	
	private long id;
	private String url;
	private String name;
	private String imagePath;
	private String imageName;
	private Category category;
	private Set<SiteReview> sitereviews = new HashSet<SiteReview>(0);
	private Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias = new HashSet<SiteReviewRatingCriteria>(0);
	private List<Topic> topics = new ArrayList<>(0);
	private Site rootSite;
	private Site backupRootSite;
	private List<Site> leafSites;

	public Site() {
	}

	public Site(long id) {
		this.id = id;
	}

	
	/**
	 * @param url
	 * @param name
	 * @param category
	 */
	public Site(String url, String name, Category category) {
		super();
		this.url = url;
		this.name = name;
		this.category = category;
	}

	/**
	 * @param url
	 * @param name
	 * @param image
	 * @param searchvector
	 * @param topic
	 * @param category
	 * @param sitereviews
	 * @param sitereviewsRatingcriterias
	 */
	public Site(String url, String name, List<Topic> topics, Category category,
			Set<SiteReview> sitereviews,
			Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias) {
		super();
		this.url = url;
		this.name = name;
		this.topics = topics;
		this.category = category;
		this.sitereviews = sitereviews;
		this.siteReviewsRatingCriterias = siteReviewsRatingCriterias;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="sites_id_seq")
	@SequenceGenerator(name="sites_id_seq", initialValue=1, sequenceName="sites_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "name")
	@Index(name="sites_name_idx")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
		this.setSortName(this.name);
	}

	@Override
	public void setSortName(String sortName){
		super.setSortName(sortName);
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "site" ,cascade = CascadeType.ALL)
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public Set<SiteReview> getSitereviews() {
		return this.sitereviews;
	}

	public void setSitereviews(Set<SiteReview> sitereviews) {
		this.sitereviews = sitereviews;
	}


	@ManyToMany(fetch=FetchType.LAZY)
	@JoinTable(name="topics_sites", joinColumns={@JoinColumn(name="site_id", nullable=false)},
			inverseJoinColumns={@JoinColumn(name="topic_id", nullable=false)})
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	/**
	 * @return the topics
	 */
	public List<Topic> getTopics() {
		return topics;
	}

	/**
	 * @param topics the topics to set
	 */
	public void setTopics(List<Topic> topics) {
		this.topics = topics;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sites", cascade = CascadeType.ALL)
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public Set<SiteReviewRatingCriteria> getSiteReviewsRatingCriterias() {
		return this.siteReviewsRatingCriterias;
	}

	public void setSiteReviewsRatingCriterias(
			Set<SiteReviewRatingCriteria> siteReviewsRatingCriterias) {
		this.siteReviewsRatingCriterias = siteReviewsRatingCriterias;
	}
	
	/**
	 * @return the image
	 */
	@Column(name="image_path", nullable=true)
	public String getImagePath() {
		return imagePath;
	}
	
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
	
	/**
	 * @return the imageName
	 */
	@Column(name="image_name", nullable=true)
	public String getImageName() {
		return imageName;
	}
	
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="rootsite_id")
	public Site getRootSite() {
		return rootSite;
	}

	public void setRootSite(Site rootSite) {
		this.rootSite = rootSite;
	}

	@OneToMany(mappedBy="rootSite", fetch = FetchType.LAZY)
	@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
	public List<Site> getLeafSites() {
		return leafSites;
	}

	public void setLeafSites(List<Site> leafSites) {
		this.leafSites = leafSites;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="backup_rootsite_id")
	public Site getBackupRootSite() {
		return backupRootSite;
	}
	
	public void setBackupRootSite(Site backupRootSite) {
		this.backupRootSite = backupRootSite;
	}
	
}
