package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TopicsRatingcriteria generated by hbm2java
 */
@Entity
@Table(name = "topics_ratingcriteria", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class TopicRatingCriteria extends CommonEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2414488980318849585L;
	
	private long id;
	private Integer weight;
	private RatingCriteria ratingCriteria;
	private Topic topic;
	
	public TopicRatingCriteria() {
	}

	public TopicRatingCriteria(long id) {
		this.id = id;
	}
	

	/**
	 * @param weight
	 * @param ratingCriteria
	 * @param topic
	 */
	public TopicRatingCriteria(Integer weight, RatingCriteria ratingCriteria,
			Topic topic) {
		super();
		this.weight = weight;
		this.ratingCriteria = ratingCriteria;
		this.topic = topic;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="topicsratingcriteria_id_seq")
	@SequenceGenerator(name="topicsratingcriteria_id_seq", initialValue=1, sequenceName="topicsratingcriteria_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ratingcriteria_id")
	public RatingCriteria getRatingCriteria() {
		return this.ratingCriteria;
	}

	public void setRatingCriteria(RatingCriteria ratingCriteria) {
		this.ratingCriteria = ratingCriteria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id")
	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Override
	public String toString() {
		return "TopicRatingCriteria [id=" + id + ", weight=" + weight
				+ ", ratingCriteria=" + ratingCriteria + ", topic=" + topic
				+ "]";
	}
}
