package com.insonix.qrata.models;

// Generated Feb 6, 2013 11:51:22 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Userinfo generated by hbm2java
 */
@Entity
@Table(name = "userinfo", schema = "public")
@Cache(usage=CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class UserInfo extends CommonEntity implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7052060978798642330L;
	
	private long id;
	private User user;
	private String bio;
	private String imagePath;
	private String imageName;
	private String firstname;
	private String lastname;
	private String email;
	
	public UserInfo() {
	}

	public UserInfo(String firstName , String lastName , String email) {
		this.firstname = firstName;
		this.lastname = lastName;
		this.email = email;
	}

	public UserInfo(long id, User user, String firstname, String lastname,
			String email, Short status, Date dateCreated, Date lastUpdated,
			Serializable uuid) {
		this.id = id;
		this.user = user;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="userinfo_id_seq")
	@SequenceGenerator(name="userinfo_id_seq", initialValue=1, sequenceName="userinfo_id_seq", allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id",nullable=false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
		this.setSortName(this.firstname);
	}
	
	@Override
	public void setSortName(String sortName){
		super.setSortName(sortName);
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 100,unique=true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the bio
	 */
	@Column(name="bio",columnDefinition="text")
	public String getBio() {
		return bio;
	}

	/**
	 * @param bio the bio to set
	 */
	public void setBio(String bio) {
		this.bio = bio;
	}

	/**
	 * @return the image
	 */
	@Column(name="image_path", nullable=true)
	public String getImagePath() {
		return imagePath;
	}
	
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}
	
	/**
	 * @return the imageName
	 */
	@Column(name="image_name", nullable=true)
	public String getImageName() {
		return imageName;
	}
	
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}
	

	@Override
	public String toString() {
		return "UserInfo [id=" + id + ", bio=" + bio + ", imagePath=" + imagePath
				+ ", firstname=" + firstname + ", lastname=" + lastname
				+ ", email=" + email + "]";
	}


}
